### ISSUE TITLE
Lumo-badge bug with ConfirmDialog

### ISSUE THREAD

**Issue by Avec112** [vaadin/vaadin-confirm-dialog#124] opened 2020-12-14 16:02 UTC
I cannot get `lumo-badge`to work with ConfirmDialog. Dialog will work.
I think this is a bug.

Also it seems `lumo-badge`can be used without import of JS and CSS inside the view.

Here is sample code:
```
@Route("test")
@PageTitle("Test")
public class TestView extends Div {

    public TestView() {
        setId("test-id");

        // Confirm Dialog
        Span span = new Span("Badge should be green");
        span.getElement().setAttribute("theme", "badge success");

        ConfirmDialog confirmDialog = new ConfirmDialog();
        confirmDialog.setCancelable(true);

        // Dialog
        Dialog dialog = new Dialog();
        dialog.setDraggable(true);
        
        // Buttons
        HorizontalLayout layout = new HorizontalLayout(
                new Button("Dialog", e -> {
                    dialog.add(span);
                    dialog.open();
                }),
                new Button("Confirm Dialog", e -> {
                    confirmDialog.add(span);
                    confirmDialog.open();
                })
        );
        layout.setJustifyContentMode(FlexComponent.JustifyContentMode.CENTER);
        layout.setPadding(true);
        add(layout);
        
    }
}

```

**Comment by jouni** [comment] 2020-12-14 16:50
This is essentially a duplicate of #106

**Comment by web-padawan** [comment] 2020-12-14 18:30
Closing in favor of #106 per above comment as the root cause is indeed the same.

**Closed by web-padawan** 2020-12-14 18:30 UTC
